### ISSUE TITLE
Bổ xung thêm bảng trạng thái gửi email

### ISSUE THREAD

**Issue by khoahp** [VietOpenCPS/doc#10]
Vấn đề

Khi hệ thống tiếp nhận yêu cầu đăng ký tài khoản hoặc hoạt động nào đó cần chức năng gửi email lại cho end user cần đưa yêu cầu gửi email vào hàng đợi, sau đó sẽ có jobs thực hiện việc quét các yêu cầu gửi email của các tài khoản chưa gửi hoặc gửi thất bại, hệ thống sẽ gửi email và cập nhật lại trạng thái gửi thành công hay thất bại vào hàng đợi.

Bảng trạng thái này cũng chỉ ra được email đó thuộc chức năng nào? Email cho đăng ký tài khoản cán bộ, đăng ký tài khoản công dân, xác nhân gửi hồ sơ thủ tục...

Cấu trúc bảng đề xuất 

```
    <column name="emailStatusId" type="long" primary="true" />

    <!-- Audit fields -->
    <column name="groupId" type="long" />


    <!-- Other fields -->

           <!-- ClassPK Liên kết đến id của đối tượng cần gửi email, vd: id đăng ký hồ sơ, id đăng ký tài khoản -->
    <column name="classPK" type="long" />
    <column name="receiveDate" type="Date" />
    <column name="sendDate" type="Date" />
            <!-- moduleId: mã module có yêu cầu gửi email -->
    <column name="moduleId" type="int"/>
    <column name="email" type="String"/>
    <column name="description" type="String"/>
            <!-- moduleId: mã trạng thái gửi email, 1 là đã gửi, 0 vừa tiếp nhận, 2 gửi thất bại -->
    <column name="statusCode" type="int"/>
```

**Comment by tanhtanhvn** [comment]
Đây là module giao tiếp. Khoa xem Liferay hiện nó đang gửi đi như thế nào. Sao không dùng lại cơ chế gửi mail hiện nay của nó mà lại làm thêm một cái nữa làm gì?
