### ISSUE TITLE
Sửa giao diện màn hình đăng ký tài khoản Doanh nghiệp

### ISSUE THREAD

**Issue by vuminhcuong** [VietOpenCPS/doc#19]
- Vào: http://qa.opencps.vn/home
- Chọn Đăng ký, Chọn [Doanh nghiệp]
- Trong màn hình Đăng kí tài khoản doanh nghiệp, sửa lại giao diện:
  1. Sửa chữ bắt buộc thành dấu \* màu đỏ như file màn hình (Màn hình: DK_002_Đăng ký tài khoản doanh nghiệp)
  2. Sửa lại khoảng cách các trường như file màn hình (Màn hình: DK_002_Đăng ký tài khoản doanh nghiệp)
- Sửa thông tin tiêu đề:
  - Thư điện tử thành "Địa chỉ thư điện tử - Email"
-  Tệp đính kèm thành "Tệp đính kèm (Giấy phép kinh doanh/Quyết định thành lập)"
- Bỏ bắt buộc các trường, chỉ giữ lại bắt buộc 3 trường: Tên đầy đủ, Thư điện tử và 
  Mã số doanh nghiệp
- Thêm dữ liệu cho phần Loại hình tổ chức gồm:
  - Công ty Cổ phần
  - Công ty trách nhiệm hữu hạn hai thành viên trở lên
  - Doanh nghiệp Tư nhân
  - Công ty trách nhiệm hữu hạn một thành viên 
  - Công ty hợp danh
  - Doanh nghiệp nhà nước
  - Hợp Tác Xã
- **File màn hình:** 
  [https://github.com/vuminhcuong/doc/tree/master/URS/Open%20CPS_Danh%20s%C3%A1ch%20m%C3%A0n%20h%C3%ACnh](https://github.com/vuminhcuong/doc/tree/master/URS/Open%20CPS_Danh%20s%C3%A1ch%20m%C3%A0n%20h%C3%ACnh)

**Comment by tanhtanhvn** [comment]
Cương phải nhập issues ở bên repo OpenCPS. Đây là repo cho doc, dev không xử lý
